version: '3'
services:
  postgres:
    image: kartoza/postgis
    restart: unless-stopped
    env_file:
      - release.env
    volumes:
      - database:/var/lib/postgresql/data
  redis:
    image: 'bitnami/redis:latest'
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-db:/bitnami/redis/data
    env_file:
      - release.env
  bot:
    build: .
    restart: unless-stopped
    env_file:
      - release.env
    depends_on:
      - postgres
      - redis

volumes:
  database:
  redis-db:
