version: '3'
services:
  postgres:
    image: kartoza/postgis
    restart: unless-stopped
    env_file:
      - release.env
    volumes:
      - database:/var/lib/postgresql/data
  redis:
    image: 'bitnami/redis:latest'
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-db:/bitnami/redis/data
    env_file:
      - release.env
  olgram:
    image: ghcr.io/civsocit/olgram/bot:stable
    restart: unless-stopped
    labels:
      - 'com.centurylinklabs.watchtower.enable="true"'
    env_file:
      - release.env
    depends_on:
      - postgres
      - redis
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.json:/config.json
    command: --interval 30


volumes:
  database:
  redis-db:
