version: '3'
services:
  postgres:
    image: kartoza/postgis
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_passwd
      - POSTGRES_DB=olgram
    ports:
      - '5400:5432'
    volumes:
      - database:/var/lib/postgresql/data
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-db:/bitnami/redis/data
    ports:
      - '6370:6379'

volumes:
  database:
  redis-db:
